# Generated by Django 4.2.1 on 2024-01-15 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofessiontags',
            options={'ordering': ['entry_date'], 'verbose_name': '用户职业标签', 'verbose_name_plural': '用户职业标签'},
        ),
    ]
