# Generated by Django 4.2.1 on 2024-01-16 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userprofessiontags_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfolders',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
