# Generated by Django 4.2.1 on 2024-01-16 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userfolders_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfolders',
            name='name',
            field=models.CharField(default='默认收藏', max_length=32, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='userfolders',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
