# Generated by Django 4.2.1 on 2024-01-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userfolders_name_alter_userfolders_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='review_plan',
            field=models.CharField(default='1,3,7,14,30', help_text="分别在多少天后复习笔记，使用','连接多个天数（如：'1,3,7,30'表示新的笔记分别在1、3、7天后进行复习）。", max_length=64, verbose_name='复习计划'),
        ),
    ]
