# Generated by Django 4.2.1 on 2024-01-17 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_review_plan'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userfolders',
            name='user_folders_uni_user_name_par',
        ),
        migrations.AddField(
            model_name='userfolders',
            name='is_private',
            field=models.BooleanField(default=False, help_text='当设置为True时，该文件夹对外不可见，并且文件夹下的子文件夹、笔记、收藏会在文件树中不可见；但非私有子文件夹、笔记、收藏仍可通过其他途径对外暴露。', verbose_name='是否私有'),
        ),
        migrations.AlterField(
            model_name='usercollections',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='user.userfolders', verbose_name='收藏夹'),
        ),
        migrations.AddConstraint(
            model_name='userfolders',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='user_folders_uni_name_par'),
        ),
    ]
