# Generated by Django 4.2.1 on 2024-01-23 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_userfavorites_userrelations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfolders',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='user.userfolders', verbose_name='父级文件夹'),
        ),
    ]
