# Generated by Django 4.2.1 on 2024-01-15 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import note.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('note', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notecomments',
            name='author',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='notecomments',
            name='note',
            field=models.ForeignKey(limit_choices_to={'is_delete': False}, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='note.note', verbose_name='笔记'),
        ),
        migrations.AddField(
            model_name='notecomments',
            name='to_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='note.notecomments', verbose_name='所回复的评论'),
        ),
        migrations.AddField(
            model_name='note',
            name='author',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='self_notes', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='note',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='self_notes', to='user.userfolders', verbose_name='所属文件夹'),
        ),
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.ForeignKey(on_delete=models.SET(note.models.set_default_tag), related_name='notes', to='note.notetag', verbose_name='标签'),
        ),
        migrations.AddIndex(
            model_name='notecomments',
            index=models.Index(fields=['create_time'], name='note_comments_idx_create_time'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['-create_time'], name='note_note_idx_create_time_desc'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['-views'], name='note_note_idx_views_desc'),
        ),
    ]
