# Generated by Django 4.2.1 on 2024-01-17 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import note.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='delete_date',
            field=models.DateField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='self_notes', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='note',
            name='tag',
            field=models.ForeignKey(blank=True, on_delete=models.SET(note.models.set_default_tag), related_name='notes', to='note.notetag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='notecomments',
            name='to_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='note.notecomments', verbose_name='所回复的评论'),
        ),
    ]
