# Generated by Django 4.2.1 on 2024-01-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_remove_note_last_review_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='last_review_feedback',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '基本忘了'), (1, '有些忘了'), (2, '基本记得'), (1, '非常清楚')], null=True, verbose_name='最近复习反馈'),
        ),
    ]
