# Generated by Django 4.2.1 on 2024-01-23 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_publish_history_alter_user_review_history'),
        ('note', '0005_alter_note_last_review_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='user.userfolders', verbose_name='所属文件夹'),
        ),
    ]
